// ======================== MOCK DATA STORE ========================

export const MOCK_SOCIETIES = [
  {
    id: "S1",
    name: "Green Valley Housing Society",
    address: "Plot 45, Sector 21, Andheri West",
    city: "Mumbai",
    state: "Maharashtra",
    pincode: "400058",
    totalFlats: 48,
    totalFloors: 12,
    regNumber: "MH/HSG/2019/4521",
    maintenanceAmount: 3500,
    maintenanceFreq: "monthly",
    maintenanceDueDay: 5,
    bankName: "HDFC Bank",
    bankAccount: "50100098765432",
    bankIfsc: "HDFC0001234",
    upiId: "greenvalley@hdfcbank",
    logo: null,
    plan: "pro",
    balance: 285000,
  },
  {
    id: "S2",
    name: "Sunshine Towers CHS",
    address: "Near IT Park, Hinjewadi Phase 2",
    city: "Pune",
    state: "Maharashtra",
    pincode: "411057",
    totalFlats: 120,
    totalFloors: 20,
    regNumber: "MH/HSG/2020/7832",
    maintenanceAmount: 4500,
    maintenanceFreq: "monthly",
    maintenanceDueDay: 10,
    bankName: "SBI",
    bankAccount: "38976543210",
    bankIfsc: "SBIN0005678",
    upiId: "sunshine@sbi",
    logo: null,
    plan: "basic",
    balance: 520000,
  },
];

export const MOCK_FLATS = [
  {
    id: "F1",
    societyId: "S1",
    flatNo: "A-204",
    floor: 2,
    block: "A",
    type: "2BHK",
    area: 950,
    ownerId: "U2",
    tenantId: "U5",
    rent: 25000,
    deposit: 75000,
    maintAmount: 3500,
    status: "occupied",
  },
  {
    id: "F2",
    societyId: "S1",
    flatNo: "A-502",
    floor: 5,
    block: "A",
    type: "3BHK",
    area: 1250,
    ownerId: "U2",
    tenantId: "U6",
    rent: 35000,
    deposit: 105000,
    maintAmount: 3500,
    status: "occupied",
  },
  {
    id: "F3",
    societyId: "S1",
    flatNo: "B-301",
    floor: 3,
    block: "B",
    type: "2BHK",
    area: 980,
    ownerId: "U3",
    tenantId: null,
    rent: 22000,
    deposit: 66000,
    maintAmount: 3500,
    status: "vacant",
  },
  {
    id: "F4",
    societyId: "S1",
    flatNo: "B-701",
    floor: 7,
    block: "B",
    type: "4BHK",
    area: 1800,
    ownerId: "U3",
    tenantId: "U7",
    rent: 55000,
    deposit: 165000,
    maintAmount: 5000,
    status: "occupied",
  },
  {
    id: "F5",
    societyId: "S2",
    flatNo: "1502",
    floor: 15,
    block: "-",
    type: "3BHK",
    area: 1350,
    ownerId: "U2",
    tenantId: null,
    rent: 30000,
    deposit: 90000,
    maintAmount: 4500,
    status: "vacant",
  },
  {
    id: "F6",
    societyId: "S1",
    flatNo: "A-101",
    floor: 1,
    block: "A",
    type: "1BHK",
    area: 650,
    ownerId: "U4",
    tenantId: "U8",
    rent: 15000,
    deposit: 45000,
    maintAmount: 3500,
    status: "occupied",
  },
];

export const MOCK_USERS = [
  {
    id: "U1",
    name: "Society Admin",
    email: "admin@greenvalley.com",
    phone: "+91 98765 00000",
    role: "society_admin",
  },
  {
    id: "U2",
    name: "Vikram Malhotra",
    email: "vikram@gmail.com",
    phone: "+91 98765 00001",
    role: "landlord",
  },
  {
    id: "U3",
    name: "Priyanka Desai",
    email: "priyanka@gmail.com",
    phone: "+91 98765 00002",
    role: "landlord",
  },
  {
    id: "U4",
    name: "Arun Joshi",
    email: "arun@gmail.com",
    phone: "+91 98765 00003",
    role: "landlord",
  },
  {
    id: "U5",
    name: "Rajesh Sharma",
    email: "rajesh@gmail.com",
    phone: "+91 98765 43210",
    role: "tenant",
  },
  {
    id: "U6",
    name: "Priya Mehta",
    email: "priya@gmail.com",
    phone: "+91 87654 32109",
    role: "tenant",
  },
  {
    id: "U7",
    name: "Amit Patel",
    email: "amit@gmail.com",
    phone: "+91 76543 21098",
    role: "tenant",
  },
  {
    id: "U8",
    name: "Neha Singh",
    email: "neha@gmail.com",
    phone: "+91 65432 10987",
    role: "tenant",
  },
  {
    id: "U9",
    name: "Suresh Kumar",
    email: "suresh@gmail.com",
    phone: "+91 98765 11111",
    role: "board_member",
  },
];

export const MOCK_BOARD_MEMBERS = [
  {
    userId: "U1",
    societyId: "S1",
    role: "admin",
    designation: "Chairman",
  },
  {
    userId: "U9",
    societyId: "S1",
    role: "board_member",
    designation: "Secretary",
  },
  {
    userId: "U3",
    societyId: "S1",
    role: "board_member",
    designation: "Treasurer",
  },
];

export const MOCK_MAINT_PAYMENTS = [
  {
    id: "MP1",
    societyId: "S1",
    flatId: "F1",
    payerId: "U2",
    amount: 3500,
    expected: 3500,
    period: "2026-03",
    status: "paid",
    date: "2026-03-04",
    method: "UPI",
  },
  {
    id: "MP2",
    societyId: "S1",
    flatId: "F2",
    payerId: "U2",
    amount: 3500,
    expected: 3500,
    period: "2026-03",
    status: "paid",
    date: "2026-03-03",
    method: "UPI",
  },
  {
    id: "MP3",
    societyId: "S1",
    flatId: "F3",
    payerId: "U3",
    amount: 0,
    expected: 3500,
    period: "2026-03",
    status: "overdue",
    date: null,
    method: null,
  },
  {
    id: "MP4",
    societyId: "S1",
    flatId: "F4",
    payerId: "U3",
    amount: 5000,
    expected: 5000,
    period: "2026-03",
    status: "paid",
    date: "2026-03-06",
    method: "Bank",
  },
  {
    id: "MP5",
    societyId: "S1",
    flatId: "F6",
    payerId: "U4",
    amount: 0,
    expected: 3500,
    period: "2026-03",
    status: "pending",
    date: null,
    method: null,
  },
];

export const MOCK_EXPENSES = [
  {
    id: "E1",
    societyId: "S1",
    category: "electricity",
    desc: "Common area electricity bill - March",
    amount: 18500,
    date: "2026-03-10",
    vendor: "MSEDCL",
    approval: "approved",
    createdBy: "U1",
  },
  {
    id: "E2",
    societyId: "S1",
    category: "cleaning",
    desc: "Monthly housekeeping - March",
    amount: 25000,
    date: "2026-03-01",
    vendor: "CleanPro Services",
    approval: "approved",
    createdBy: "U9",
  },
  {
    id: "E3",
    societyId: "S1",
    category: "lift_maintenance",
    desc: "Lift annual maintenance contract",
    amount: 45000,
    date: "2026-03-15",
    vendor: "Otis Elevator",
    approval: "approved",
    createdBy: "U1",
  },
  {
    id: "E4",
    societyId: "S1",
    category: "security",
    desc: "Security guards salary - March",
    amount: 48000,
    date: "2026-03-01",
    vendor: "SecureGuard Agency",
    approval: "approved",
    createdBy: "U1",
  },
  {
    id: "E5",
    societyId: "S1",
    category: "plumbing",
    desc: "Main pipeline repair - Block A",
    amount: 12000,
    date: "2026-03-12",
    vendor: "Local plumber",
    approval: "pending",
    createdBy: "U9",
  },
];

export const MOCK_TICKETS = [
  {
    id: "TK-2603-001",
    societyId: "S1",
    flatId: "F1",
    raisedBy: "U5",
    assignedTo: "U9",
    category: "plumbing",
    subject: "Water leakage in bathroom ceiling",
    priority: "high",
    status: "in_progress",
    created: "2026-03-18",
  },
  {
    id: "TK-2603-002",
    societyId: "S1",
    flatId: "F4",
    raisedBy: "U7",
    assignedTo: null,
    category: "lift",
    subject: "Lift B stuck on 5th floor twice this week",
    priority: "urgent",
    status: "open",
    created: "2026-03-20",
  },
  {
    id: "TK-2603-003",
    societyId: "S1",
    flatId: "F2",
    raisedBy: "U6",
    assignedTo: "U9",
    category: "parking",
    subject: "Visitor parking always occupied by residents",
    priority: "medium",
    status: "assigned",
    created: "2026-03-15",
  },
  {
    id: "TK-2603-004",
    societyId: "S1",
    flatId: "F6",
    raisedBy: "U8",
    assignedTo: "U9",
    category: "noise",
    subject: "Construction noise from A-205 after 10 PM",
    priority: "medium",
    status: "resolved",
    created: "2026-03-10",
  },
];

export const MOCK_PARKING = [
  {
    id: "PK1",
    societyId: "S1",
    slot: "A-01",
    type: "car",
    level: "B1",
    flatId: "F1",
    vehicle: "MH 02 AB 1234",
    vehicleType: "car",
    model: "Honda City",
    status: "occupied",
  },
  {
    id: "PK2",
    societyId: "S1",
    slot: "A-02",
    type: "car",
    level: "B1",
    flatId: "F2",
    vehicle: "MH 02 CD 5678",
    vehicleType: "car",
    model: "Hyundai Creta",
    status: "occupied",
  },
  {
    id: "PK3",
    societyId: "S1",
    slot: "B-01",
    type: "car",
    level: "B1",
    flatId: "F4",
    vehicle: "MH 12 EF 9012",
    vehicleType: "car",
    model: "Toyota Innova",
    status: "occupied",
  },
  {
    id: "PK4",
    societyId: "S1",
    slot: "B-02",
    type: "car",
    level: "B1",
    flatId: null,
    vehicle: null,
    vehicleType: null,
    model: null,
    status: "available",
  },
  {
    id: "PK5",
    societyId: "S1",
    slot: "V-01",
    type: "visitor",
    level: "Ground",
    flatId: null,
    vehicle: null,
    vehicleType: null,
    model: null,
    status: "available",
  },
  {
    id: "PK6",
    societyId: "S1",
    slot: "BK-01",
    type: "bike",
    level: "B1",
    flatId: "F6",
    vehicle: "MH 02 GH 3456",
    vehicleType: "bike",
    model: "Royal Enfield",
    status: "occupied",
  },
];

export const MOCK_POLLS = [
  {
    id: "PL1",
    societyId: "S1",
    title: "Should we install EV charging stations?",
    desc: "2 stations proposed in basement parking",
    options: [
      { id: "y", text: "Yes, proceed" },
      { id: "n", text: "No, unnecessary" },
      { id: "l", text: "Yes, but next year" },
    ],
    eligible: ["landlord"],
    ends: "2026-04-01",
    status: "active",
    votes: { y: 12, n: 3, l: 8 },
    totalVoters: 23,
    createdBy: "U1",
  },
  {
    id: "PL2",
    societyId: "S1",
    title: "Diwali celebration budget approval",
    desc: "Proposed budget: ₹1,50,000 from society fund",
    options: [
      { id: "a", text: "Approve ₹1.5L" },
      { id: "r", text: "Reduce to ₹1L" },
      { id: "d", text: "Decline" },
    ],
    eligible: ["landlord"],
    ends: "2026-03-25",
    status: "active",
    votes: { a: 18, r: 7, d: 2 },
    totalVoters: 27,
    createdBy: "U9",
  },
];

export const MOCK_NOTICES = [
  {
    id: "N1",
    societyId: "S1",
    title: "Water tank cleaning scheduled",
    content:
      "Water supply will be interrupted on 25th March from 10 AM to 4 PM for annual tank cleaning.",
    type: "maintenance",
    audience: "all",
    date: "2026-03-20",
    createdBy: "U1",
  },
  {
    id: "N2",
    societyId: "S1",
    title: "AGM Notice - Annual General Meeting",
    content:
      "The Annual General Meeting is scheduled for 5th April 2026 at 6 PM in the community hall. All landlords are requested to attend.",
    type: "general",
    audience: "landlords",
    date: "2026-03-18",
    createdBy: "U1",
  },
  {
    id: "N3",
    societyId: "S1",
    title: "Maintenance increase proposal",
    content:
      "Due to rising costs, a proposal to increase monthly maintenance from ₹3,500 to ₹4,000 will be discussed in the AGM.",
    type: "financial",
    audience: "landlords",
    date: "2026-03-15",
    createdBy: "U9",
  },
];

export const MOCK_RENT_PAYMENTS = [
  {
    id: "RP1",
    tenantName: "Rajesh Sharma",
    flatNo: "A-204",
    amount: 25000,
    expected: 25000,
    month: "Mar 2026",
    status: "paid",
    date: "2026-03-01",
    method: "UPI",
  },
  {
    id: "RP2",
    tenantName: "Priya Mehta",
    flatNo: "A-502",
    amount: 0,
    expected: 35000,
    month: "Mar 2026",
    status: "overdue",
    date: null,
    method: null,
  },
  {
    id: "RP3",
    tenantName: "Amit Patel",
    flatNo: "B-701",
    amount: 55000,
    expected: 55000,
    month: "Mar 2026",
    status: "paid",
    date: "2026-03-05",
    method: "Bank",
  },
  {
    id: "RP4",
    tenantName: "Neha Singh",
    flatNo: "A-101",
    amount: 15000,
    expected: 15000,
    month: "Mar 2026",
    status: "paid",
    date: "2026-03-03",
    method: "UPI",
  },
];

// Website content
export const WEBSITE_STATS = [
  { value: "12,000+", label: "Housing Societies", icon: "🏢" },
  { value: "1.1 Cr", label: "Rental Properties in India", icon: "🏠" },
  { value: "₹15,000 Cr", label: "Market Opportunity", icon: "💰" },
  { value: "90%", label: "Still Manual Operations", icon: "📋" },
];

export const WEBSITE_FEATURES = [
  {
    icon: "💰",
    title: "Smart Rent Collection",
    desc: "Automatic WhatsApp reminders with UPI payment links and instant receipts. No more chasing tenants for rent.",
    category: "landlord",
    color: "forest",
  },
  {
    icon: "🏢",
    title: "Society Maintenance",
    desc: "Auto-generate monthly maintenance, collect online, track defaulters. Secretary's job made 10x easier.",
    category: "society",
    color: "brand",
  },
  {
    icon: "📄",
    title: "AI Agreement Generator",
    desc: "Legal templates for 8 cities. Draft ready in 2 minutes. Lawyer review at ₹499. Registration support at ₹999.",
    category: "landlord",
    color: "purple",
  },
  {
    icon: "🚫",
    title: "Complaint Ticket System",
    desc: "Plumbing, lift, parking — raise a ticket, track it, auto-escalate if not resolved on time.",
    category: "society",
    color: "red",
  },
  {
    icon: "🅿️",
    title: "Parking Management",
    desc: "Digital slot allocation, vehicle mapping, visitor parking — no more parking disputes.",
    category: "society",
    color: "blue",
  },
  {
    icon: "🗳️",
    title: "Online Voting & Polls",
    desc: "EV charging station? Budget approval? Online secret ballot with transparent results.",
    category: "society",
    color: "purple",
  },
  {
    icon: "📱",
    title: "WhatsApp Native",
    desc: "Reminders, receipts, notices, ticket updates — all on WhatsApp. No new app to download.",
    category: "all",
    color: "forest",
  },
  {
    icon: "📊",
    title: "Financial Reports",
    desc: "Monthly income, expense breakdown, tax summary — CA-ready reports. One-click PDF download.",
    category: "landlord",
    color: "brand",
  },
  {
    icon: "📋",
    title: "Expense Management",
    desc: "Upload bill photos, select category, get board approval. Every record digitized.",
    category: "society",
    color: "blue",
  },
  {
    icon: "🤝",
    title: "Tenant Lifecycle",
    desc: "Add tenant → Auto credentials via WhatsApp → Auto-deactivate at lease end. Full lifecycle managed.",
    category: "landlord",
    color: "forest",
  },
  {
    icon: "📢",
    title: "Notice Board",
    desc: "Water tank cleaning? AGM meeting? Official notice with one-click WhatsApp broadcast.",
    category: "society",
    color: "red",
  },
  {
    icon: "🔒",
    title: "Document Vault",
    desc: "Agreements, KYC, society rules, minutes — secure cloud storage with role-based access.",
    category: "all",
    color: "purple",
  },
];

export const WEBSITE_TESTIMONIALS = [
  {
    name: "Rajiv Mehta",
    role: "Society Chairman, Green Valley CHS, Mumbai",
    text: "Maintenance collection used to take 15 days. Now 90% is collected in 3 days. WhatsApp reminders are game-changing.",
    avatar: "RM",
  },
  {
    name: "Sunita Sharma",
    role: "Landlord, 4 Properties, Delhi-NCR",
    text: "I manage 4 flats across 3 societies. Used to go crazy with Excel and WhatsApp groups. Now one dashboard handles everything.",
    avatar: "SS",
  },
  {
    name: "Amit Kumar",
    role: "Tenant, Sunshine Towers, Pune",
    text: "Paying rent is so easy now — link arrives on WhatsApp, pay via UPI, receipt comes instantly. No more awkward cash handovers.",
    avatar: "AK",
  },
  {
    name: "Deepak Joshi",
    role: "Secretary, Royal Heights, Bangalore",
    text: "The complaint system is the best. People used to call me at 10 PM. Now they raise tickets, track them. Very professional.",
    avatar: "DJ",
  },
  {
    name: "Priya Desai",
    role: "Treasurer, Lake View Society, Hyderabad",
    text: "We had no expense tracking system. Now every bill has a photo, category, and approval. No tension during audits.",
    avatar: "PD",
  },
];

export const WEBSITE_SOCIETY_PRICING = [
  {
    name: "Starter",
    price: "₹2,999",
    period: "/month",
    desc: "Small societies (up to 30 flats)",
    features: [
      "30 flats management",
      "Maintenance collection",
      "Complaint tickets",
      "WhatsApp reminders (500/mo)",
      "Basic reports",
      "Email support",
    ],
    popular: false,
    cta: "Start Free Trial",
  },
  {
    name: "Professional",
    price: "₹5,999",
    period: "/month",
    desc: "Medium societies (up to 100 flats)",
    features: [
      "100 flats management",
      "Everything in Starter",
      "Expense management + approval",
      "Parking management",
      "Polls & voting",
      "WhatsApp reminders (2,000/mo)",
      "Document vault",
      "Priority support",
    ],
    popular: true,
    cta: "Start Free Trial",
  },
  {
    name: "Enterprise",
    price: "₹9,999",
    period: "/month",
    desc: "Large societies (unlimited flats)",
    features: [
      "Unlimited flats",
      "Everything in Professional",
      "Multi-wing/tower support",
      "WhatsApp unlimited",
      "Custom reports",
      "Dedicated account manager",
      "API access",
      "On-call support",
    ],
    popular: false,
    cta: "Contact Sales",
  },
];

export const WEBSITE_LANDLORD_PRICING = [
  {
    name: "Basic",
    price: "₹499",
    period: "/month",
    desc: "Up to 3 properties",
    features: [
      "3 property management",
      "Rent collection + tracking",
      "Tenant management",
      "WhatsApp reminders",
      "Payment receipts",
      "Basic reports",
    ],
    popular: false,
    cta: "Start Free Trial",
  },
  {
    name: "Pro",
    price: "₹999",
    period: "/month",
    desc: "Up to 10 properties",
    features: [
      "10 property management",
      "Everything in Basic",
      "Agreement generator (free drafts)",
      "Tax-ready reports",
      "Multi-society view",
      "Priority support",
    ],
    popular: true,
    cta: "Start Free Trial",
  },
  {
    name: "NRI",
    price: "₹1,999",
    period: "/month",
    desc: "Unlimited + remote management",
    features: [
      "Unlimited properties",
      "Everything in Pro",
      "NRI tax reports",
      "Dedicated manager",
      "Monthly property inspection reports",
      "Video call support",
    ],
    popular: false,
    cta: "Start Free Trial",
  },
];

export const WEBSITE_FAQS = [
  {
    q: "What is RentSaathi?",
    a: "RentSaathi is an all-in-one platform that manages the entire relationship between housing societies, landlords, and tenants — rent collection, maintenance, complaints, parking, voting, agreements — all in one place.",
  },
  {
    q: "Does the tenant need to download any app?",
    a: "No! Tenants don't need to download anything. Everything arrives on WhatsApp — payment links, receipts, notices. They can also log in via browser to view their dashboard.",
  },
  {
    q: "How does payment work? Where does the money go?",
    a: "Tenants pay via UPI/card — the money goes directly to the landlord/society bank account via Razorpay (T+2 days). 0% commission on UPI. RentSaathi never holds the money.",
  },
  {
    q: "Is the agreement generator legally valid?",
    a: "We provide AI-powered draft templates — they become legally valid when printed on stamp paper and registered. Lawyer review at ₹499 and full registration support at ₹999 are also available.",
  },
  {
    q: "Can one landlord use it across multiple societies?",
    a: "Yes! A landlord can have 10 different flats in 5 different societies — all managed from one dashboard.",
  },
  {
    q: "Is there a free trial?",
    a: "Yes! 14-day free trial — no credit card required. Both society and landlord plans are available for trial.",
  },
  {
    q: "Is the data secure?",
    a: "100%. Supabase (PostgreSQL) database with Row Level Security — every society's data is isolated. Aadhaar/PAN data is encrypted. Bank-level security.",
  },
  {
    q: "Who sends the WhatsApp messages?",
    a: "Messages are sent from your (society/landlord) WhatsApp Business number. Tenants see your business name. RentSaathi works in the background.",
  },
];

export const WEBSITE_HOW_IT_WORKS = [
  {
    step: "1",
    icon: "📝",
    title: "Register",
    desc: "Society admin or landlord — sign up in 2 minutes. Add society details, bank account, connect WhatsApp.",
  },
  {
    step: "2",
    icon: "🏠",
    title: "Add Flats & Tenants",
    desc: "Add your society flats. Assign landlords. Add tenants — they automatically get login credentials via WhatsApp.",
  },
  {
    step: "3",
    icon: "📱",
    title: "It Runs Automatically",
    desc: "Monthly automatic rent/maintenance reminders. Payment links on WhatsApp. Auto-generated receipts. Auto-tracked complaints.",
  },
  {
    step: "4",
    icon: "📈",
    title: "View Reports, Relax",
    desc: "Dashboard shows everything — income, pending amounts, expenses. Tax reports ready. Stress-free property management.",
  },
];
